source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’

pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'AFNetworking'
pod 'FMDB'
pod 'BlocksKit'
pod 'TPKeyboardAvoiding'
pod 'RBBAnimation'
pod 'INTULocationManager'
pod 'DateTools'
pod 'UITableView+FDTemplateLayoutCell'
pod 'CCLogSystem'
pod 'JTMaterialTransition'
pod 'SMPageControl'
pod 'XTSafeCollection'
pod 'ReactiveCocoa', '2.5'
pod 'FXBlurView'